site_name: Serverless Python Demo OPN305
site_description: Serverless Python Demo for re:Invent OPN305 session
site_author: Ran Isenberg and Heitor Lessa
repo_url: https://github.com/ran-isenberg/serverless-python-demo
edit_uri: edit/main/docs

nav:
  - Homepage:
      - index.md
      - Decision log: decision_log.md
      - API reference:
          - Stream Processor: api/stream_processor.md
          - Product models: api/product_models.md
      - Monitoring: monitoring.md
      - Pipeline: pipeline.md
      - Open Source: opensource.md


theme:
  name: material
  font:
    text: Ubuntu
  palette:
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    - header.autohide
    - navigation.sections
    - navigation.top
    - navigation.instant
    - navigation.indexes
    - navigation.tracking
    - content.code.annotate
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      linenums: true
  - pymdownx.details
  - pymdownx.snippets:
      base_path: "."
      check_paths: true
  - meta
  - toc:
      permalink: true
      toc_depth: 4
  - attr_list
  - pymdownx.emoji
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

copyright: Copyright &copy; 2025 Ran Isenberg and Heitor Lessa

plugins:
  - git-revision-date
  - search
  - render_swagger
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom

watch:
  - product
  - docs
